### ISSUE TITLE
Tracking issue: find all mutations

### ISSUE THREAD

**Issue by willcrichton** [willcrichton/flowistry#28]
- [ ] Implement core analysis
  - [ ] Determine reusability of existing code
- [ ] Implement VSCode support
- [ ] Add unit tests + VSC tests

**Comment by willcrichton** [comment]
@connorff we can use this space to track issues / PRs / questions / etc related to your next project.

**Comment by willcrichton** [comment]
This has been implemented!
