### ISSUE TITLE
The Flowistry Todo List

### ISSUE THREAD

**Issue by willcrichton** [willcrichton/flowistry#33]
# Features
* [ ] Windows support 
  * [ ] Fix span bugs? is this related to unicode? document.offsetAt seems character based and not byte-based
  * [ ] Add windows target to release builds
  * [ ] Should fix #27

# Bugs
* [ ] #31
* [ ] #32

# Performance

For reference, here's a subset of slow calls when running the command in rust-lang/rust:

```
focus compiler/rustc_typeck/src/check/op.rs 21361
```

![Screen Shot 2022-02-16 at 11 13 25 AM](https://user-images.githubusercontent.com/663326/154338637-7a46e829-62b3-4baf-bebd-02a6d8da0313.png)

* [ ] Create a benchmark to track Flowistry performance. Should include granular information on which pieces are bottlenecks.
  * [ ] Program with many lifetimes (in inputs / in body) to stress alias analysis
  * [ ] Program with many instructions to stress infoflow analysis
  * [ ] Program with giant data structures to test any code relying on `Place::interior_*`
* Possible opportunities for optimization:
  * [ ] Loading `TyCtxt` can take a while, e.g. 2.5s for rustc_typeck. What's causing this? Can it be made more incremental?
  * [ ] Polonius is slow, are there any low hanging fruit we can upstream into datafrog?

**Comment by tangowithfoxtrot** [comment]
Could I humbly request that support for [Helix](https://github.com/helix-editor/helix) be added to that list as well?

This is a really cool tool and I'd love to be able to use it in my favorite editor one day.

**Comment by thomascjohnson** [comment]
Hi Will, this is brilliant work. This is a question from a place of ignorance, so forgive me if it doesn't make sense, but could this be packaged as a language server to work alongside rust analyzer? That seems like it would be an easier path to work with more IDEs.

**Comment by GoldsteinE** [comment]
> could this be packaged as a language server to work alongside rust analyzer

I’m planning on trying to implement a Neovim plugin, and this is one of the options I’ve considered. You could implement it via semantic tokens, but it will only be available in editors that support LSP highlighting, which excludes e.g. Zed and helix. I’m also not sure how well non-Neovim editors support multiple LSPs attached to the same buffer.

**Comment by thomascjohnson** [comment]
I am confused about LSP highlighting being unavailable in Zed. Is that due to the tree sitter setup they have?

**Comment by GoldsteinE** [comment]
It's just not implemented, see https://github.com/zed-industries/zed/issues/7450

**Comment by Jirubizu** [comment]
> > could this be packaged as a language server to work alongside rust analyzer
> 
> I’m planning on trying to implement a Neovim plugin, and this is one of the options I’ve considered. You could implement it via semantic tokens, but it will only be available in editors that support LSP highlighting, which excludes e.g. Zed and helix. I’m also not sure how well non-Neovim editors support multiple LSPs attached to the same buffer.

Please, I just came across this project but as someone who's been using vim/neovim for years, I don't want to make the transition over to a new editor just to get access to this 😅

**Comment by willcrichton** [comment]
I don't have the bandwidth to refactor the plugin architecture, but I would happily accept a contribution from anyone who wants to take that on.

**Comment by thomascjohnson** [comment]
> It's just not implemented, see [zed-industries/zed#7450](https://github.com/zed-industries/zed/issues/7450)

That was merged!

**Comment by jakubsuchybio** [comment]
So can we have this for zed please? 😅
